name: wuon
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  universal_html: ^2.3.0
  # Обновлено до Null Safety версии
  json_annotation: ^4.8.1
  dart_midi_pro: ^1.0.4+2
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: 85dde09b702a0cb1f5e1392d2f030bdc3d4e5be3
  file_selector: ^1.0.0
  kana_kit: ^2.0.0
  path: ^1.7.0
  flutter_audio_desktop:
    path: ../flutter_audio_desktop
  synaps_flutter:
    path: ../wsynaps/flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  # Обновлено для поддержки современного Dart
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  synaps_generator:
    path: ../synaps/generator

flutter:
  uses-material-design: true
