import "dart:io";

import "package:flutter/material.dart";
import 'package:wuon/actions/base.dart';
import "package:synaps_flutter/synaps_flutter.dart";
import "package:wuon/controllers/muonnote.dart";
import "package:wuon/controllers/muonproject.dart";
import 'package:wuon/logic/helpers.dart';
import "package:wuon/serializable/muon.dart";
import "package:wuon/logic/musicxml.dart";
import "package:flutter_audio_desktop/flutter_audio_desktop.dart";

part "muonvoice.g.dart";

@Controller()
class MuonVoiceController with WeakEqualityController {
  late MuonProjectController project;

  /// Folder name of the voice model this voice uses
  @Observable()
  String modelName = MuonHelpers.getDefaultVoiceModel();

  /// Randomise timings of this vocal on each render (for use as a backing
  /// vocal for harmonies)
  /// 
  /// TODO: actually use this value
  @Observable()
  bool randomiseTiming = false;

  /// The list of all of the notes that this voice sings
  @Observable()
  List<MuonNoteController> notes = [];

  /// Internally used to check if a recompile is required for preview
  bool hasChangedNoteData = true;

  /// Exports this voice to a MusicXML class
  MusicXML exportVoiceToMusicXML() {
    return project.exportVoiceToMusicXML(this);
  }

  /// Sorts all of the notes in this voice chronologically
  void sortNotesByTime() {
    notes.sort((a,b) => a.startAtTime.compareTo(b.startAtTime));
  }

  /// Helper method to add a note into this voice, and create an action
  void addNote(MuonNoteController note) {
    addNoteInternal(note);
    final action = AddNoteAction(note);
    project.addAction(action);
  }

  /// Helper method to add a note into this voice, and also updates the
  /// note's reference to this voice
  void addNoteInternal(MuonNoteController note) {
    note.voice = this;
    notes.add(note);
  }

  /// Internal list of voice colors
  static final noteColors = [
    Colors.blue,
    Colors.purple,
    Colors.amber,
    Colors.indigo,
    Colors.green,
    Colors.teal,
    Colors.brown,
  ];

  /// The UI color of this voice
  get color {
    final voiceID = (project != null ? project.voices.indexOf(this) : -1) + 1;
    return noteColors[voiceID % noteColors.length];
  }

  /// The base filename to use for files generated by this voice
  String get voiceFileName => project.projectFileNameNoSpacesNoExt + "_" + project.voices.indexOf(this).toString() + "_voice";

  /// Creates Neutrino-compatible labels for this voice by first exporting
  /// to a MusicXML file, and then running `musicXMLtoLabel.exe`
  Future<void> makeLabels() async {
    final musicXML = exportVoiceToMusicXML();
    final musicXMLString = MusicXMLUtils.serializeMusicXML(musicXML);

    if(!Directory(project.getProjectFilePath("musicxml/")).existsSync()) {
      Directory(project.getProjectFilePath("musicxml/")).createSync();
    }

    if(!Directory(project.getProjectFilePath("label/")).existsSync()) {
      Directory(project.getProjectFilePath("label/")).createSync();
    }

    if(!Directory(project.getProjectFilePath("label/full/")).existsSync()) {
      Directory(project.getProjectFilePath("label/full/")).createSync();
    }

    if(!Directory(project.getProjectFilePath("label/mono/")).existsSync()) {
      Directory(project.getProjectFilePath("label/mono/")).createSync();
    }

    final musicXMLPath = project.getProjectFilePath("musicxml/" + voiceFileName + ".musicxml");

    File(musicXMLPath)
      .writeAsStringSync(musicXMLString);

    await Process.run(MuonHelpers.getProgramPath("musicXMLtoLabel"), [
      musicXMLPath,
      project.getProjectFilePath("label/full/" + voiceFileName + ".lab"),
      project.getProjectFilePath("label/mono/" + voiceFileName + ".lab"),
      "-x",
      MuonHelpers.getRawProgramPath("settings/dic"),
    ]).then((ProcessResult results) {
      print(results.stdout);
    });
  }

  /// Generates f0/melspec/wav files by executing Neutrino
  /// Requires labels to be already generated, and currently does
  /// not check whether labels already exist!
  /// 
  /// TODO: check if labels exist
  Future<void> runNeutrino() async {
    if(!Directory(project.getProjectFilePath("neutrino/")).existsSync()) {
      Directory(project.getProjectFilePath("neutrino/")).createSync();
    }

    if(!Directory(project.getProjectFilePath("label/timing/")).existsSync()) {
      Directory(project.getProjectFilePath("label/timing/")).createSync();
    }

    if(!Directory(project.getProjectFilePath("audio/")).existsSync()) {
      Directory(project.getProjectFilePath("audio/")).createSync();
    }

    final neutrinoDir = MuonHelpers.getRawProgramPath("");
    await Process.run(
      MuonHelpers.getProgramPath("neutrino"), [
        project.getProjectFilePath("label/full/" + voiceFileName + ".lab"),
        project.getProjectFilePath("label/timing/" + voiceFileName + ".lab"),
        project.getProjectFilePath("neutrino/" + voiceFileName + ".f0"),
        project.getProjectFilePath("neutrino/" + voiceFileName + ".melspec"),
        project.getProjectFilePath("audio/" + voiceFileName + ".wav"),
        MuonHelpers.getRawProgramPath("model/" + modelName + "/"),
        "-n","8",
        "-k","0",
        "-m",
        "-t",
      ],
      environment: {
        "LD_LIBRARY_PATH": "${neutrinoDir}bin:${neutrinoDir}NSF/bin",
      },
    ).then((ProcessResult results) {
      print(results.stdout);
      print(results.stderr);
    });
  }

  AudioPlayer? audioPlayer;
  int audioPlayerDuration = 0;
  Future<AudioPlayer?> getAudioPlayer([Duration? playPos]) async {
    final voiceID = project.voices.indexOf(this);
    if(audioPlayer == null) {
      audioPlayer = new AudioPlayer(id: voiceID);
    }

    await audioPlayer!.unload();
    try {
      await audioPlayer!.load(AudioSource.fromFile(File(project.getProjectFilePath("audio/" + voiceFileName + ".wav"))));
      audioPlayerDuration = (await audioPlayer!.duration).inMilliseconds;
      await audioPlayer!.setPosition(playPos ?? Duration(seconds: 2));
    } catch (e) {
      audioPlayer = null;
    }

    return audioPlayer;
  }

  MuonVoice toSerializable([MuonProject? project]) {
    final out = MuonVoice();
    out.project = project ?? this.project.toSerializable();
    out.modelName = this.modelName;
    out.randomiseTiming = this.randomiseTiming;
    for(final note in notes) {
      out.notes.add(note.toSerializable());
    }
    return out;
  }

  static MuonVoiceController fromSerializable(MuonVoice obj, [MuonProjectController? project]) {
    final out = MuonVoiceController().ctx();
    out.project = project ?? MuonProjectController.fromSerializable(obj.project);
    out.modelName = obj.modelName;
    out.randomiseTiming = obj.randomiseTiming;
    for(final note in obj.notes) {
      out.addNoteInternal(MuonNoteController.fromSerializable(note));
    }
    return out;
  }
}
